### ISSUE TITLE
At The Root link leads to a defunct domain

### ISSUE THREAD

**Issue by Denperidge** [ContributorCovenant/ethicalsource#143]
Hi! Wanted to check out At The Root, but the currently active link seems to not lead to a functional website.

https://github.com/EthicalSource/ethicalsource.dev/blob/56d7df4ae77373f61c64512b78426dfe575bbf89/content/licenses/_index.md?plain=1#L10

**Comment by CoralineAda** [comment]
Hi there, thanks for letting us know about this! I have contacted the At the Root team and apparently the domain accidentally lapsed. Hopefully everything gets resolved soon.
