### ISSUE TITLE
Unnecessarily inflammatory language

### ISSUE THREAD

**Issue by shaunagm** [ContributorCovenant/ethicalsource#17]
The [landing page](https://ethicalsource.dev/) says: 

> We’ve seen the Open Source Initiative prioritizing software freedom over [basic human rights](https://twitter.com/OpenSourceOrg/status/1176229398929977344).

I may be biased due to my personal relationships with members of the OSI, but this seems like a mischaracterization.  OSI merely (and correctly) pointed that the license under discussion did not meet the terms of an open source license and that calling it open source was therefore confusing.

I appreciate the boldness of this statement overall but find this particular sentence misleading and alienating.

**Comment by CoralineAda** [comment]
That's a great observation. Is there language that you have in mind that would make the point more fairly?

**Comment by shaunagm** [comment]
I'm trying to come up with something that doesn't dive down a rabbit hole. Most people who support existing free/open source software definitions _do_ value human rights but don't think software licensing is the way to protect them. I've heard this said dozens of times but it's not written anywhere on OSI's site that I can find to link to, and I'm wary of putting words in their mouth.  I think FSF's website does articulate this, but I haven't looked and anyway, FSF and OSI are not interchangeable.

Provided I/we can source it, maybe something like, "The Open Source Initiative doesn't believe that software licenses can be used to protect basic human rights"?

I'm also not a huge fan of the existing statement "And the organizations that claim ownership of the definitions of free and open source software have ignored their obligations to the community."  It's not clear to me that FSF or OSI is obliged to alter their licenses to meet these demands (although obviously FSF had other obligations that they failed).  I would say something like, "The organizations that claim ownership of the definitions of free and open source software have not led on these issues."

When phrased this way the actual conflict is more clear.  The existing leaders of the FOSS movement, by and large, do not want to alter the existing licenses because they don't believe doing so will actually protect human rights (or perhaps they believe it will protect human rights only a little bit, and at too great a cost).  They haven't led because they don't think we'll get anywhere.

Those of us interested in exploring alternatives believe that there is at least a possibility that licenses could be used in this way.  I suspect that if we proposed a robust alternative and showed that it worked, many FOSS fans would adopt the new license/system.

**Comment by CoralineAda** [comment]
I'll take a stab at this tonight and cross-reference a PR with this issue. Thanks for your thoughtfulness around this, I greatly appreciate it.

**Comment by CoralineAda** [comment]
@shaunagm Check the new language?

**Comment by shaunagm** [comment]
Hi @CoralineAda, sorry for the delay - notifications from this repo were being sent to my spam folder, for some reason.  

The language in your PR certainly looks better to me.  Please don't consider me a blocker in merging the PR.
