### ISSUE TITLE
Fourth definition needs a definition for "unethical"

### ISSUE THREAD

**Issue by danimesq** [ContributorCovenant/ethicalsource#23]
https://ethicalsource.dev/definition/

"Its creators have the right to prohibit its use by individuals or organizations engaged in human rights violations or other behavior that they deem unethical".

Right to prohibit use when there are human rights violations is ok.
But here is a hole which enables censorship: "or other behavior that they deem unethical".

You should define which "unethical" considerations from community is valid or not.

**Comment by ror3d** [comment]
Agree. It might need some restraints on what things are considered ethical or not.

With this definition, a pro-life could restrict the use of software to pro-choice people, for example. Or try to exclude communities like LGBTQ+ on the grounds that they promote "unethical practices".

I suppose the problem arises depending on what's the basis of someone's ethical system, as mentioned [in this article](https://hackernoon.com/6-myths-about-ethical-open-source-licenses-3bfbd042b1dc). There might be disagreement between those, but then we might also find ourselves with ethic systems based on religion, which opens a can of worms.

I don't know how some restriction against that should be worded though.

**Comment by danimesq** [comment]
ethicalsource needs a definition standard for "unethical" to be followed when prohibiting uses/forks.
"My right to use my hand ends when your nose begins". If the freedom haves no limitations, it attacks freedom itself; as everything, when in excess, is bad.

A LGBT advertising on TV, even in a hour kids could be watching (Russia prohibits any LGBT ads, and is the country with the highest number of attacks), isn't unethical. A Christianity advertising also isn't unethical (remember what ISIS did against both LGBT and Christians). LGBT, Christian and any other kind of advertising only begins to be unethical when they preach intolerance against the tolerant.
I believe people in essence are all equal. They varies in gender, color, form, sexual orientation, desires and any other sentimental characteristic (also shared with irrational animals). LGBT in essence is about loving. Christianity in essence is about loving. Any other classes and religions with such essence is also about loving. For me, ethical-source is to protect both tolerant humans and animals from intolerance.

**Comment by ror3d** [comment]
Exactly, so there needs to be a basic definition of what ethical and unethical entails, so any "unethical" thing the creator decides on can be evaluated as valid or not under the definition.

There are clearly unethical things, as you said, imposing intolerant acts on other people is clearly unethical. Defending from those is not.

But then you come across various "trolley problems", and other impossible decisions. I would say that ruling over those might be more questionable, either from the definition or from a license.

I don't know if this makes sense, it's a bit difficult for me to put properly into words.

**Comment by danimesq** [comment]
@CoralineAda, your turn?

**Comment by UncannyBingo** [comment]
Being addressed in #33.

**Comment by robbyoconnor** [comment]
#4 is still problematic...in fact it's where the entire Ethical Source definition can take an ugly turn. It's basically Thy Software Shall be Christian -- you ran on the assumption that everyone thinks like you and they do not. Your definition of what Ethical Source about means I can make a license that forbids anybody who is LGBTQ+ from using my software. 


There's also a typo and I'll be damned if my name goes anywhere near the commit logs. This is an ill-fated venture and won't stop ICE. Your definition of Ethical Source is weak and open to hostile interpretations. 

I posted a twitter thread where I tore this one apart and pointed out only a few of the ways it could go wrong.

**Comment by elimisteve** [comment]
@robbyoconnor I think the recently-merged https://github.com/EthicalSource/ethicalsource.dev/pull/37/files solves your critique. Just as before, no one can prevent anti-humanitarian licenses from being created by the malicious; they just won't meet any definition of "Ethical Source".

Got any more critiques aside from your obsolete Twitter thread?

**Comment by elimisteve** [comment]
@DaniellMesquita @rorlork I had the same concern over much older definitions of "Ethical Source"! But the latest definition _rocks_, IMO. If you think you've spotted any more holes, please feel free to say so.

**Comment by robbyoconnor** [comment]
Does it though? Because the United Nations Universal Declaration of
Human Rights is not meant to be used like this. It's not a part of
international law in any way, shape, or form. You might be able to get
away with using https://en.wikipedia.org/wiki/International_Convention_on_the_Elimination_of_All_Forms_of_Racial_Discrimination but that's also not universally accepted since not all countries have
signed onto it.

**Comment by robbyoconnor** [comment]
If you want to ensure that discrimination doesn't happen, make sure whatever you use has the effect of international law behind it.
