### ISSUE TITLE
I need some guiding on usage of terms

### ISSUE THREAD

**Issue by ror3d** [ContributorCovenant/ethicalsource#25]
Together with the problems that unethical uses of software brings, I've been seeing other kinds of complaints around open-source lately. Mostly on the fact that big companies like Amazon use foss to gain a great amount of money while not actually contributing anything back to the projects that they use for that.

[License zero](https://licensezero.com/) tries to solve that but it doesn't solve the rest of ethical problems that are being treated here.

My idea to try to avoid things like that would be a license that would be free to use for most cases, but that required some kind of contribution to the project in cases where the company's revenue depended on the software being developed or maintained, for example. With some kind of escalation, it's not the same for a 2-person startup to use the software than it is for Amazon.

The thing is, as it is, the definition for ethical source wouldn't allow for this kind of license, since it wouldn't be free to use for *all* uses that didn't go against the definition, and I don't think it allows to restrict for commercial usage either. So my question: is what would be the way to get something like that to work in an easy way?

**Comment by UncannyBingo** [comment]
Howdy! Sorry you got left hanging. Your concerns have been echoed by many, and the new revision to the ESD in #33 should address it!

**Comment by ror3d** [comment]
Yes, I think it does, thank you!
