### ISSUE TITLE
EthicalSource belongs on GitLab, not GitHub 

### ISSUE THREAD

**Issue by robbyoconnor** [ContributorCovenant/ethicalsource#46]
If Ethical Source's goal is to stop those who support ICE and the DOD, then why are you hosting everything on here? Use GitLab. 

GitHub is owned by MS, who has ICE contracts.

**Comment by zspencer** [comment]
This is an excellent question. I believe there is one reason that GitHub was chosen, and another reason for why moving may not be an effective use of the organizations limited time and attention.

1. Moving to GitLab or a self-hosted option would be more ideologically pure; but ideological purity is only so effective at shifting the Overton window. To engage with the existing developer community in good-faith, we must show up where the community exists. This may include using products or services that are also used by organizations which we would not work with directly.

2. Migrating from Vendor A to Vendor B is unlikely to significantly reduce the amount of "water" the ethical source movement carries for actors whose ethics we disagree with. For example, GitLab [demonstrates sexism](https://www.theregister.co.uk/2020/02/06/gitlab_sales_women/).

There is a saying: "There is no ethical consumption under capitalism." This is not an excuse, but to the best of my knowledge there is not an intersectional, community-owned and operated alternative to GitHub or GitLab. It there were, I would be happy to explore, advocate for and perform the work to migrate to such a platform so long as it does not reduce community engagement and is [within the movements financial means](https://opencollective.com/ethical-source).

**Comment by robbyoconnor** [comment]
> This is an excellent question. I believe there is one reason that GitHub was chosen, and another reason for why moving may not be an effective use of the organizations limited time and attention.
> 
> 1. Moving to GitLab or a self-hosted option would be more ideologically pure; but ideological purity is only so effective at shifting the Overton window. To engage with the existing developer community in good-faith, we must show up where the community exists. This may include using products or services that are also used by organizations which we would not work with directly.
> 2. Migrating from Vendor A to Vendor B is unlikely to significantly reduce the amount of "water" the ethical source movement carries for actors whose ethics we disagree with. For example, GitLab [demonstrates sexism](https://www.theregister.co.uk/2020/02/06/gitlab_sales_women/).
> 
> There is a saying: "There is no ethical consumption under capitalism." This is not an excuse, but to the best of my knowledge there is not an intersectional, community-owned and operated alternative to GitHub or GitLab. It there were, I would be happy to explore, advocate for and perform the work to migrate to such a platform so long as it does not reduce community engagement and is [within the movements financial means](https://opencollective.com/ethical-source).

Well...not quite. You don't want ICE using tech right? MS has an ICE contract....

**Comment by zspencer** [comment]
@robbyoconnor, this reply fails to address my statements in any meaningful way; and simply re-asserts your conclusion. Would you be willing to respond to the comments I made in a meaningful and direct way? 

If not, I would request that we close this issue so that we can move forward with the task at hand of withholding the public commons from abusive actors. 

Otherwise, the goalposts will continuously shift as we learn more and more about how broadly human rights abusers permeate the technology service provider landscape.

**Comment by robbyoconnor** [comment]
All licenses like this will do is create business risks and kill off projects entirely.

**Comment by zspencer** [comment]
I agree that is a valid risk that we should work to mitigate. It does not appear to be related to the issue at hand, so I appreciate you choosing to close this topic.

I have created the following issue to discuss the relative important of mitigating these risks; as well as what tactics we can evaluate in order to do so: https://github.com/EthicalSource/ethicalsource.dev/issues/51

**Comment by decentral1se** [comment]
Hey y'all just to mention, that it is important to consider that we shouldn't be on Github. I work-own at https://autonomic.zone and we'd be interested in discussing taking on hosting this organisation over at https://git.autonomic.zone. There are other hosting providers that would work.

**Comment by decentral1se** [comment]
Opened https://github.com/EthicalSource/ethicalsource.dev/issues/61 to follow up.
