### ISSUE TITLE
Write post on kicking off the wg.hippocratic.copyleft

### ISSUE THREAD

**Issue by decentral1se** [ContributorCovenant/ethicalsource#60]
Will take this on :partying_face:

**Comment by octocat69** [comment]
https://linuxcommandlibrary.com/man/add-apt-repository.html#:~:text=repository%20--enable-source%20%5B-,repository_spec%5D,-SYNOPSIS

**Comment by decentral1se** [comment]
Won't be doing this, probably should just close it.
