### ISSUE TITLE
Migrate from Github

### ISSUE THREAD

**Issue by decentral1se** [ContributorCovenant/ethicalsource#61]
Follow on from https://github.com/EthicalSource/ethicalsource.dev/issues/46 to re-frame without Gitlab.com which also has questionable business practices and relies on Microsoft infrastructure so is actually not a solution.

I also dropped the comment regarding Autonomic hosting: https://github.com/EthicalSource/ethicalsource.dev/issues/46#issuecomment-633102574.

However, there are others!

- https://codeberg.org
- https://framagit.org
- https://git.coop

Can take on this migration if there is consensus behind it.

**Comment by zspencer** [comment]
I'd be curious about the social costs of migrating from Github (which is the most active community of developers) to a platform that may have even more barriers to discovery / participation.

Do you know if any of the self-hostable projects have a strong experience design culture? I'd hate to move to a platform that's even _less_ human-friendly than Github, especially if it means we'd be even less accessible and collaborative with non-programmery folks.

**Comment by CoralineAda** [comment]
As @zspencer said, there is a significant social cost to leaving GitHub, not to mention the security and administration capabilities that the platform gives us. "There is no ethical consumption under capitalism," but we can subvert the tools and bend them to good. 

To be clear, this is not something that I want us to pursue. I don't think it's worth the lift and the risk.

**Comment by decentral1se** [comment]
Ah, should have been clearer. I didn't mean leave, but to move to another "primary" hosting and then mirror everything back to Github (all popular alternatives offer this out of the box and sync automatically so there is no admin overhead). https://gitea.io/en-us/ has feature parity on UI/UX, security and adminstration.

What I want to emphasis is that there is a significant cognitive dissonance in relying on Github as the sole provider of infrastructure for this project. Yes, we need to be here for the purposes of outreach, no question. Issue trackers can remain open, we're all mostly stuck on Github for $work anyway. 

The main organisational work can go on @ the community alternative. Gitea and self-hosted Gitlab have a "Login with Github" button so when people want to come over, they just log in with their existing account. 


Do understand where you're both coming from though but it's less overhead than you think and I think it sends a strong message on organisational tactics.

**Comment by zspencer** [comment]
@decentral1se I'd be happy to discuss pricing for managed hosting for https://github.com/zinc-collective. I'd much rather migrate to a cooperatively owned managed infrastructure provider; especially if we can move documents, email, etc. off of Google. Mind sending me an email? zee@zinc.coop

**Comment by decentral1se** [comment]
Will drop you a line today @zspencer!

https://mastodon.ar.al/@aral/104225016650077568 is related :+1: 

Will leave this off now, happy Monday folks.
