### ISSUE TITLE
Enable RSS

### ISSUE THREAD

**Issue by kemitchell** [ContributorCovenant/ethicalsource#66]
Is that as easy as deleting this line from config?

https://github.com/EthicalSource/ethicalsource.dev/blob/e61b4b7087db12b300ac3c85ed1adc66044f3b14/config.toml#L5

**Comment by klaude** [comment]
@kemitchell, I think I got this working in #77. Take a look at https://deploy-preview-77--ethicalsource.netlify.app/ and let me know if that's what you're looking for.
